CREATE DATABASE emp;
DROP DATABASE emp;
CREATE DATABASE emp;
USE emp;
CREATE TABLE employee(empno INT(10) PRIMARY KEY NOT NULL,empname VARCHAR(20) NOT NULL,dept VARCHAR(20) NOT NULL,salary INT NOT NULL,branch VARCHAR(20) NOT NULL);
ALTER TABLE employee ADD dob DATE NOT NULL;
INSERT INTO employee(empno,empname,dept,salary,dob,branch)VALUES(101,'amit','production',45000,'2000-03-12','banglore');
INSERT INTO employee(empno,empname,dept,salary,dob,branch)VALUES(102,'amit','hr',70000,'2002-07-03','banglore');
INSERT INTO employee(empno,empname,dept,salary,dob,branch)VALUES(103,'sunita','manager',120000,'2001-01-11','banglore');
INSERT INTO employee(empno,empname,dept,salary,dob,branch)VALUES(104,'sunita','it',67000,'2001-08-01','mysore');
INSERT INTO employee(empno,empname,dept,salary,dob,branch)VALUES(105,'makesh','civil',145000,'2003-09-20','mumbai');
SELECT * FROM employee;
SELECT empno,salary FROM employee;
SELECT AVG(salary) FROM employee;
SELECT COUNT(empno) FROM employee;
SELECT COUNT(DISTINCT empname)FROM employee;
SELECT SUM(salary),empname,COUNT(empname) FROM employee GROUP BY empname HAVING COUNT(empname)>1;
SELECT * FROM employee WHERE salary>120000;
SELECT empname FROM employee ORDER BY empname DESC;
SELECT * FROM employee WHERE empname="amit" AND salary>50000;
